"""phase8_documents_softdelete

Revision ID: 740d8d2b126b
Revises: 91e0bd1d167b
Create Date: 2026-08-13 10:27:20.063882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '740d8d2b126b'
down_revision: Union[str, None] = '91e0bd1d167b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_deleted', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('is_deleted')

    # ### end Alembic commands ###
