"""phase8_documents

Revision ID: 91e0bd1d167b
Revises: 4c691e9815d3
Create Date: 2026-08-13 10:24:26.323993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = '91e0bd1d167b'
down_revision: Union[str, None] = '4c691e9815d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.Enum('SALES_ORDER', 'PURCHASE_ORDER', 'INVOICE', 'PARTNER', 'PRODUCT', 'GENERAL', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_documents_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_entity_id'), ['entity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_entity_type'), ['entity_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_id'))
        batch_op.drop_index(batch_op.f('ix_documents_entity_type'))
        batch_op.drop_index(batch_op.f('ix_documents_entity_id'))
        batch_op.drop_index(batch_op.f('ix_documents_company_id'))

    op.drop_table('documents')
    # ### end Alembic commands ###
