"""phase4_procurement

Revision ID: d25146f9dac6
Revises: 992766ffabea
Create Date: 2026-08-12 15:31:10.322863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

revision: str = 'd25146f9dac6'
down_revision: Union[str, None] = '992766ffabea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_requests',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('pr_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='prstatus'), nullable=False),
    sa.Column('requester_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_requests_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_requests_pr_number'), ['pr_number'], unique=False)

    op.create_table('purchase_orders',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('supplier_id', sa.String(length=36), nullable=False),
    sa.Column('po_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'ISSUED', 'PARTIALLY_RECEIVED', 'RECEIVED', 'CANCELLED', name='postatus'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pr_id', sa.String(length=36), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requests.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_orders_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_orders_po_number'), ['po_number'], unique=False)

    op.create_table('purchase_request_items',
    sa.Column('pr_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pr_id'], ['purchase_requests.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_request_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_request_items_id'), ['id'], unique=False)

    op.create_table('goods_receipts',
    sa.Column('company_id', sa.String(length=36), nullable=False),
    sa.Column('po_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goods_receipts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipts_company_id'), ['company_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goods_receipts_receipt_number'), ['receipt_number'], unique=False)

    op.create_table('purchase_order_items',
    sa.Column('po_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('received_quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['po_id'], ['purchase_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_order_items_id'), ['id'], unique=False)

    op.create_table('goods_receipt_items',
    sa.Column('receipt_id', sa.String(length=36), nullable=False),
    sa.Column('po_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['po_item_id'], ['purchase_order_items.id'], ),
    sa.ForeignKeyConstraint(['receipt_id'], ['goods_receipts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goods_receipt_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goods_receipt_items_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goods_receipt_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipt_items_id'))

    op.drop_table('goods_receipt_items')
    with op.batch_alter_table('purchase_order_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_items_id'))

    op.drop_table('purchase_order_items')
    with op.batch_alter_table('goods_receipts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goods_receipts_receipt_number'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_id'))
        batch_op.drop_index(batch_op.f('ix_goods_receipts_company_id'))

    op.drop_table('goods_receipts')
    with op.batch_alter_table('purchase_request_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_request_items_id'))

    op.drop_table('purchase_request_items')
    with op.batch_alter_table('purchase_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_orders_po_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_orders_company_id'))

    op.drop_table('purchase_orders')
    with op.batch_alter_table('purchase_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_requests_pr_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_requests_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_requests_company_id'))

    op.drop_table('purchase_requests')
    # ### end Alembic commands ###
